stages:

    featurize:
        cmd: python3 src/featurize.py assets/data/raw/
        deps:
            - assets/data/raw
            - src/featurize.py
            - src/config.py
        outs:
            - assets/data/featurized
            - assets/output/feature_vector_timestamps.npy
            - assets/output/combined.csv
        params:
            - featurize.columns
            - featurize.dataset
            - featurize.overlap
            - featurize.timestamp_column
            - featurize.convert_timestamp_to_datetime
            - featurize.window_size

    cluster:
        cmd: python3 src/cluster.py assets/data/featurized/
        deps:
            - assets/data/featurized
            - assets/data/annotations
            - src/cluster.py
            - src/config.py
        outs:
            - assets/output/labels.csv
            - assets/output/event_log.csv
            - assets/output/feature_vectors.csv
            - assets/output/cluster_names.csv
            - assets/models
        params:
            - cluster.learning_method
            - cluster.max_iter
            - cluster.n_clusters
            - cluster.use_predefined_centroids
            - cluster.fix_predefined_centroids
            - cluster.annotations_dir
            - cluster.min_segment_length

    evaluate:
        cmd: python3 src/evaluate.py
        deps:
            - assets/data/featurized
            - assets/models/model.pkl
            - assets/output/labels.csv
            - assets/output/feature_vector_timestamps.npy
            - assets/output/combined.csv
            - src/evaluate.py
            - src/config.py
        outs:
            - assets/plots/clusters.png
            - assets/plots/labels_over_time.html
    #     metrics:
    #     - assets/metrics/metrics.json

